# Project Name
TARGET = ex_crossfade

# Sources
CPP_SOURCES = ex_crossfade.cpp

# Library Locations
LIBDAISY_DIR = $(LIBDAISY)/libdaisy
DAISYSP_DIR = ../../

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY)/core
include $(SYSTEM_FILES_DIR)/makefile

