# Project Name
TARGET = ex_bypass

# Sources
CPP_SOURCES = ex_bypass.cpp

# Library Locations
DAISYSP_DIR ?= ../../../DaisySP
LIBDAISY_DIR ?= ../../../libdaisy

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

