# Project Name
TARGET = ex_bypass

# Sources
CPP_SOURCES = ex_bypass.cpp

# Library Locations
LIBDAISY_DIR = ../../../libdaisy
DAISYSP_DIR = ../../

# Core location, and generic makefile.
SYSTEM_FILES_DIR = ../../../core
include $(SYSTEM_FILES_DIR)/makefile

