# Project Name
TARGET = ex_adenv

# Sources
CPP_SOURCES = ex_adenv.cpp

# Library Locations
DAISYSP_DIR = ../../
LIBDAISY_DIR ?= $(LIBDAISY)/libdaisy/

# Core location, and generic Makefile.
# Overwrite LIBDAISY Environment variable to the location of the lib on your machine.
SYSTEM_FILES_DIR = $(LIBDAISY)/core
include $(SYSTEM_FILES_DIR)/Makefile

