# Project Name
TARGET = ex_adenv

# Sources
CPP_SOURCES = ex_adenv.cpp

# Library Locations
LIBDAISY_DIR ?= $(LIBDAISY)/libdaisy/
DAISYSP_DIR = ../../

# Core location, and generic makefile.
# Overwrite LIBDAISY Environment variable to the location of the lib on your machine.
SYSTEM_FILES_DIR = $(LIBDAISY)/core
include $(SYSTEM_FILES_DIR)/Makefile

