# Project Name
TARGET = ex_compressor

# Sources
CPP_SOURCES = ex_compressor.cpp

# Library Locations
LIBDAISY_DIR = ../../../libdaisy
DAISYSP_DIR = ../../

# Core location, and generic makefile.
SYSTEM_FILES_DIR = ../../../core
include $(SYSTEM_FILES_DIR)/Makefile

