# Project Name
TARGET = ex_tone

# Sources
CPP_SOURCES = ex_tone.cpp

# Library Locations
LIBDAISY_DIR = $(LIBDAISY)/libdaisy
DAISYSP_DIR = ../../

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY)/core
include $(SYSTEM_FILES_DIR)/Makefile

