# Project Name
TARGET = ex_reverbsc

# Sources
CPP_SOURCES = ex_reverbsc.cpp

# Library Locations
LIBDAISY_DIR = $(LIBDAISY)/libdaisy
DAISYSP_DIR = ../../

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY)/core
include $(SYSTEM_FILES_DIR)/Makefile

